/** Country geography for nationwide ("whole country") alert scope.
 *
 * Two lookups, both keyed on the ISO2 code the rest of the app already uses
 * (`LocationBlock.country`, the rights perimeters, `reference.py`):
 *
 *  - `ISO3` — because the map's country polygons are keyed on ISO3, not ISO2.
 *  - `CENTROID` — a representative point, because `LocationBlock.lat/lng` are
 *    required and the marker clustering, `flyTo` and map search all rely on
 *    every location having coordinates.
 *
 * Both tables live in `countryData.ts`, generated by `ops/build_geo.py` from the
 * same Natural Earth release that produces the province/city overlay. They were
 * hand-written while SWAN was Africa-only (54 entries); at 238 they have to be
 * derived, and deriving them from the map's own source is what stops a country
 * being offered in a picker that the map can't draw.
 */
export { ISO3, CENTROID } from './countryData'
import { ISO3 } from './countryData'

/** ISO2 → ISO3 (`ISO3`)
 *
 * The dashboard's base map draws country polygons from MapLibre's demotiles
 * (`source-layer: 'countries'`, see lib/mapStyle.ts), and that layer identifies
 * countries by `ADM0_A3` — Natural Earth's own code, which is *not* always the
 * ISO 3166-1 alpha-3 code. South Sudan is the one that bit us: ISO says `SSD`,
 * the tiles say `SDS`, and the hand-written table had `SSD`, so a nationwide
 * South Sudan alert painted nothing at all and looked exactly like "no alert
 * here". Generating the table from `ADM0_A3` removes the whole class of bug;
 * `warnOnUnmatchedCountries` in lib/mapOverlay.ts catches the remainder in dev.
 *
 * Nine microstates and territories (Vatican City, Nauru, Tuvalu, Gibraltar,
 * Macau, Anguilla, Saint Barthélemy, Pitcairn, US Minor Outlying Islands) have
 * no polygon in the demotiles world tile — they are sub-pixel at that scale.
 * A nationwide highlight there paints nothing; a point-scope location still
 * works normally.
 */

/** ISO2 → [lng, lat] label point (`CENTROID`)
 *
 * Natural Earth's `LABEL_X`/`LABEL_Y` — cartographic label anchors, chosen to
 * sit *inside* the landmass. Deliberately not derived from the `places`
 * gazetteer: that table is ports and coastal cities, so averaging it drags
 * every centroid out to sea (Nigeria's would land in the Bight of Benin).
 * These only have to place a marker sensibly inside the country.
 */

/** The synthetic place code a nationwide block carries.
 *
 * Marker clustering keys on `location.code` (see `buildClusters`), so every
 * nationwide block for a country must share one code to collapse into a single
 * marker — and it must not collide with a real LOCODE from the gazetteer.
 */
/** ADM0_A3 -> ISO2, the reverse of `ISO3`.
 *
 * Built from the generated table rather than written out, so it cannot drift
 * from it. Needed by the zone editor, which reads country features straight out
 * of the basemap tiles to suggest a zone's perimeter: the tiles hand back
 * `ADM0_A3` and every rights decision in SWAN is keyed on ISO2.
 */
export const ISO2_FROM_ISO3: Record<string, string> = Object.fromEntries(
  Object.entries(ISO3).map(([iso2, a3]) => [a3, iso2]),
)

export function nationwideCode(country: string): string {
  return `${country.toUpperCase()}-NATIONWIDE`
}
