-- =====================================================================
--  SWAN — seed the `places` gazetteer (location master data)
--  The create-alert location picker types ahead against this table.
--  Empty table = no location can ever be chosen = no alert can be made.
--  Safe to re-run (idempotent).
-- =====================================================================

INSERT INTO places (code, name, country, lat, lng, aliases, created_at) VALUES
  ('MZBEW', 'Beira', 'MZ', -19.83, 34.84, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('MZMPM', 'Maputo', 'MZ', -25.97, 32.57, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('MZMNC', 'Nacala', 'MZ', -14.54, 40.67, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('CIABJ', 'Abidjan', 'CI', 5.32, -4.02, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('CISPY', 'San-Pédro', 'CI', 4.75, -6.64, '["san pedro"]'::json, (now() AT TIME ZONE 'utc')),
  ('NGAPP', 'Lagos — Apapa', 'NG', 6.45, 3.36, '["apapa"]'::json, (now() AT TIME ZONE 'utc')),
  ('NGTIN', 'Tin Can Island', 'NG', 6.44, 3.34, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('NGONN', 'Onne', 'NG', 4.7, 7.15, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('GHTEM', 'Tema', 'GH', 5.67, 0.02, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('GHTKD', 'Takoradi', 'GH', 4.88, -1.75, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('ZADUR', 'Durban', 'ZA', -29.87, 31.03, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('ZACPT', 'Cape Town', 'ZA', -33.9, 18.43, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('ZAPLZ', 'Port Elizabeth', 'ZA', -33.96, 25.63, '["gqeberha"]'::json, (now() AT TIME ZONE 'utc')),
  ('KEMBA', 'Mombasa', 'KE', -4.04, 39.67, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('KENBO', 'Nairobi ICD', 'KE', -1.32, 36.85, '["nairobi"]'::json, (now() AT TIME ZONE 'utc')),
  ('TZDAR', 'Dar es Salaam', 'TZ', -6.82, 39.28, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('EGSUZ', 'Suez Canal', 'EG', 30.03, 32.55, '["suez"]'::json, (now() AT TIME ZONE 'utc')),
  ('EGALY', 'Alexandria', 'EG', 31.2, 29.92, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('CDKAS', 'Kasumbalesa border', 'CD', -12.25, 27.8, '["kasumbalesa"]'::json, (now() AT TIME ZONE 'utc')),
  ('CDMAT', 'Matadi', 'CD', -5.82, 13.46, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('SNDKR', 'Dakar', 'SN', 14.68, -17.42, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('CMDLA', 'Douala', 'CM', 4.05, 9.7, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('AOLAD', 'Luanda', 'AO', -8.78, 13.24, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('AOLOB', 'Lobito', 'AO', -12.35, 13.55, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('NAWVB', 'Walvis Bay', 'NA', -22.96, 14.51, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('TGLFW', 'Lomé', 'TG', 6.13, 1.29, '["lome"]'::json, (now() AT TIME ZONE 'utc')),
  ('BJCOO', 'Cotonou', 'BJ', 6.35, 2.42, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('MAPTM', 'Tanger Med', 'MA', 35.88, -5.52, '["tangier", "tanger"]'::json, (now() AT TIME ZONE 'utc')),
  ('MACAS', 'Casablanca', 'MA', 33.6, -7.62, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('DJJIB', 'Port of Djibouti', 'DJ', 11.6, 43.14, '["djibouti"]'::json, (now() AT TIME ZONE 'utc')),
  ('CNSGH', 'Shanghai', 'CN', 31.233, 121.483, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('CNNBO', 'Ningbo', 'CN', 29.867, 121.55, '["zhoushan"]'::json, (now() AT TIME ZONE 'utc')),
  ('CNSNZ', 'Shenzhen', 'CN', 22.55, 114.117, '["yantian"]'::json, (now() AT TIME ZONE 'utc')),
  ('CNGGZ', 'Guangzhou', 'CN', 23.133, 113.233, '["nansha"]'::json, (now() AT TIME ZONE 'utc')),
  ('CNQIN', 'Qingdao', 'CN', 36.05, 120.317, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('CNTNJ', 'Tianjin', 'CN', 39.033, 117.2, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('CNXAM', 'Xiamen', 'CN', 24.45, 118.1, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('CNDAL', 'Dalian', 'CN', 38.917, 121.6, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('HKHKG', 'Hong Kong', 'HK', 22.317, 114.167, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('SGSIN', 'Singapore', 'SG', 1.283, 103.85, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('KRPUS', 'Busan', 'KR', 35.133, 129.05, '["pusan"]'::json, (now() AT TIME ZONE 'utc')),
  ('KRINC', 'Incheon', 'KR', 37.45, 126.617, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('JPTYO', 'Tokyo', 'JP', 35.683, 139.75, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('JPYOK', 'Yokohama', 'JP', 35.45, 139.65, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('JPUKB', 'Kobe', 'JP', 34.683, 135.167, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('JPGTK', 'Nagoya', 'JP', 35.233, 136.85, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('TWKHH', 'Kaohsiung', 'TW', 22.565, 120.307, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('MYPKG', 'Port Klang', 'MY', 3.0, 101.4, '["klang"]'::json, (now() AT TIME ZONE 'utc')),
  ('MYTPP', 'Tanjung Pelepas', 'MY', 1.367, 103.55, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('THLCH', 'Laem Chabang', 'TH', 13.083, 100.883, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('THBKK', 'Bangkok', 'TH', 13.75, 100.517, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('VNSGN', 'Ho Chi Minh City', 'VN', 10.767, 106.667, '["saigon"]'::json, (now() AT TIME ZONE 'utc')),
  ('VNHPH', 'Haiphong', 'VN', 20.85, 106.683, '["hai phong"]'::json, (now() AT TIME ZONE 'utc')),
  ('IDTPP', 'Tanjung Priok', 'ID', -6.104, 106.88, '["jakarta"]'::json, (now() AT TIME ZONE 'utc')),
  ('IDSUB', 'Surabaya', 'ID', -7.233, 112.75, '["tanjung perak"]'::json, (now() AT TIME ZONE 'utc')),
  ('PHMNL', 'Manila', 'PH', 14.524, 120.943, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('INNSA', 'Nhava Sheva', 'IN', 18.949, 72.951, '["jnpt", "jawaharlal nehru", "mumbai"]'::json, (now() AT TIME ZONE 'utc')),
  ('INMUN', 'Mundra', 'IN', 22.839, 69.717, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('INMAA', 'Chennai', 'IN', 13.083, 80.283, '["madras"]'::json, (now() AT TIME ZONE 'utc')),
  ('INCOK', 'Cochin', 'IN', 9.966, 76.243, '["kochi"]'::json, (now() AT TIME ZONE 'utc')),
  ('LKCMB', 'Colombo', 'LK', 6.917, 79.85, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('BDCGP', 'Chittagong', 'BD', 22.308, 91.801, '["chattogram"]'::json, (now() AT TIME ZONE 'utc')),
  ('PKKHI', 'Karachi', 'PK', 24.835, 66.974, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('AEJEA', 'Jebel Ali', 'AE', 25.01, 55.061, '["dubai"]'::json, (now() AT TIME ZONE 'utc')),
  ('AEAUH', 'Abu Dhabi', 'AE', 24.467, 54.367, '["khalifa port"]'::json, (now() AT TIME ZONE 'utc')),
  ('SAJED', 'Jeddah', 'SA', 21.467, 39.167, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('SADMM', 'Dammam', 'SA', 26.5, 50.2, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('OMSOH', 'Sohar', 'OM', 24.378, 56.738, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('OMSLL', 'Salalah', 'OM', 16.942, 54.003, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('QAHMD', 'Hamad Port', 'QA', 25.01, 51.605, '["doha"]'::json, (now() AT TIME ZONE 'utc')),
  ('KWSWK', 'Shuwaikh', 'KW', 29.35, 47.933, '["kuwait"]'::json, (now() AT TIME ZONE 'utc')),
  ('IQUQR', 'Umm Qasr', 'IQ', 30.033, 47.933, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('IRBND', 'Bandar Abbas', 'IR', 27.183, 56.267, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('TRAMR', 'Ambarli', 'TR', 40.967, 28.7, '["istanbul"]'::json, (now() AT TIME ZONE 'utc')),
  ('TRMER', 'Mersin', 'TR', 36.717, 34.633, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('TRIZM', 'Izmir', 'TR', 38.417, 27.15, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('NLRTM', 'Rotterdam', 'NL', 51.917, 4.5, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('BEANR', 'Antwerp', 'BE', 51.217, 4.417, '["antwerpen"]'::json, (now() AT TIME ZONE 'utc')),
  ('DEHAM', 'Hamburg', 'DE', 53.517, 9.933, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('DEBRV', 'Bremerhaven', 'DE', 53.533, 8.6, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('FRLEH', 'Le Havre', 'FR', 49.5, 0.1, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('FRMRS', 'Marseille', 'FR', 43.3, 5.4, '["fos"]'::json, (now() AT TIME ZONE 'utc')),
  ('ESVLC', 'Valencia', 'ES', 39.444, -0.318, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('ESALG', 'Algeciras', 'ES', 36.148, -5.4, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('ESBCN', 'Barcelona', 'ES', 41.355, 2.169, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('ITGOA', 'Genoa', 'IT', 44.417, 8.95, '["genova"]'::json, (now() AT TIME ZONE 'utc')),
  ('ITGIT', 'Gioia Tauro', 'IT', 38.417, 15.9, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('ITTRS', 'Trieste', 'IT', 45.645, 13.754, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('GRPIR', 'Piraeus', 'GR', 37.933, 23.617, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('GBFXT', 'Felixstowe', 'GB', 51.955, 1.313, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('GBSOU', 'Southampton', 'GB', 50.903, -1.424, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('GBLIV', 'Liverpool', 'GB', 53.417, -3.0, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('IEDUB', 'Dublin', 'IE', 53.344, -6.206, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('PTLIS', 'Lisbon', 'PT', 38.717, -9.133, '["lisboa"]'::json, (now() AT TIME ZONE 'utc')),
  ('PTSIE', 'Sines', 'PT', 37.95, -8.867, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('PLGDN', 'Gdansk', 'PL', 54.393, 18.669, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('SEGOT', 'Gothenburg', 'SE', 57.717, 11.967, '["goteborg"]'::json, (now() AT TIME ZONE 'utc')),
  ('DKCPH', 'Copenhagen', 'DK', 55.667, 12.583, '["kobenhavn"]'::json, (now() AT TIME ZONE 'utc')),
  ('NOOSL', 'Oslo', 'NO', 59.9, 10.733, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('FIHEL', 'Helsinki', 'FI', 60.167, 24.933, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('RULED', 'St Petersburg', 'RU', 59.905, 30.244, '["saint petersburg"]'::json, (now() AT TIME ZONE 'utc')),
  ('RUNVS', 'Novorossiysk', 'RU', 44.717, 37.767, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('UAODS', 'Odesa', 'UA', 46.5, 30.75, '["odessa"]'::json, (now() AT TIME ZONE 'utc')),
  ('LTKLJ', 'Klaipeda', 'LT', 55.687, 21.134, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('LVRIX', 'Riga', 'LV', 57.008, 24.088, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('HRRJK', 'Rijeka', 'HR', 45.333, 14.4, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('SIKOP', 'Koper', 'SI', 45.548, 13.733, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('MTMAR', 'Marsaxlokk', 'MT', 35.833, 14.533, '["malta freeport"]'::json, (now() AT TIME ZONE 'utc')),
  ('USLAX', 'Los Angeles', 'US', 34.05, -118.25, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('USLGB', 'Long Beach', 'US', 33.767, -118.183, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('USNYC', 'New York', 'US', 40.7, -74.0, '["newark", "new jersey"]'::json, (now() AT TIME ZONE 'utc')),
  ('USTSA', 'Savannah', 'US', 35.217, -88.233, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('USHOU', 'Houston', 'US', 29.75, -95.35, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('USSEA', 'Seattle', 'US', 47.602, -122.36, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('USTIW', 'Tacoma', 'US', 47.267, -122.404, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('USORF', 'Norfolk', 'US', 36.902, -76.293, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('USCHS', 'Charleston', 'US', 32.822, -79.924, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('USOAK', 'Oakland', 'US', 37.799, -122.301, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('USMIA', 'Miami', 'US', 25.775, -80.167, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('USMSY', 'New Orleans', 'US', 29.934, -90.056, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('USBAL', 'Baltimore', 'US', 39.283, -76.617, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('CAVAN', 'Vancouver', 'CA', 49.289, -123.112, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('CAMTR', 'Montreal', 'CA', 45.544, -73.525, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('CAHAL', 'Halifax', 'CA', 44.657, -63.574, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('MXZLO', 'Manzanillo', 'MX', 19.05, -104.3, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('MXLZC', 'Lazaro Cardenas', 'MX', 17.95, -102.183, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('MXVER', 'Veracruz', 'MX', 19.2, -96.083, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('PABLB', 'Balboa', 'PA', 8.956, -79.569, '["panama canal"]'::json, (now() AT TIME ZONE 'utc')),
  ('PACTB', 'Cristobal', 'PA', 9.35, -79.9, '["colon", "panama canal"]'::json, (now() AT TIME ZONE 'utc')),
  ('BRSSZ', 'Santos', 'BR', -23.933, -46.317, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('BRRIO', 'Rio de Janeiro', 'BR', -22.867, -43.217, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('BRPNG', 'Paranagua', 'BR', -25.5, -48.517, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('BRITJ', 'Itajai', 'BR', -26.9, -48.65, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('ARBUE', 'Buenos Aires', 'AR', -34.583, -58.667, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('CLSAI', 'San Antonio', 'CL', -33.6, -71.6, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('CLVAP', 'Valparaiso', 'CL', -33.033, -71.633, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('PECLL', 'Callao', 'PE', -12.05, -77.133, '["lima"]'::json, (now() AT TIME ZONE 'utc')),
  ('COCTG', 'Cartagena', 'CO', 10.403, -75.526, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('COBUN', 'Buenaventura', 'CO', 3.883, -77.053, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('ECGYE', 'Guayaquil', 'EC', -2.167, -79.9, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('UYMVD', 'Montevideo', 'UY', -34.901, -56.204, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('JMKIN', 'Kingston', 'JM', 17.982, -76.825, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('DOCAU', 'Caucedo', 'DO', 18.417, -69.633, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('BSFPO', 'Freeport', 'BS', 26.538, -78.728, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('AUSYD', 'Sydney', 'AU', -33.85, 151.2, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('AUMEL', 'Melbourne', 'AU', -37.817, 144.967, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('AUBNE', 'Brisbane', 'AU', -27.467, 153.017, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('AUFRE', 'Fremantle', 'AU', -32.047, 115.738, '["perth"]'::json, (now() AT TIME ZONE 'utc')),
  ('NZAKL', 'Auckland', 'NZ', -36.833, 174.8, '[]'::json, (now() AT TIME ZONE 'utc')),
  ('NZTRG', 'Tauranga', 'NZ', -37.683, 176.167, '[]'::json, (now() AT TIME ZONE 'utc'))
ON CONFLICT (code) DO UPDATE SET
  name    = EXCLUDED.name,
  country = EXCLUDED.country,
  lat     = EXCLUDED.lat,
  lng     = EXCLUDED.lng,
  aliases = EXCLUDED.aliases;

-- Verify: expect 150
SELECT count(*) AS places FROM places;
